In [9]:
# 1) Crear un array z1=[3x4] lleno de ceros tipo entero

In [8]:
import numpy  as np
z1 = np.zeros([3,4],dtype='int32')
z1


array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
# 2) Crear un array z2 3x4 lleno de ceros salvo la primera fila que serán todos unos.

In [29]:
arr1= np.ones([1,4],dtype='int32') 
arr2= np.zeros([2,4],dtype='int32') 
z2 =np.concatenate((arr1, arr2))  
z2

array([[1, 1, 1, 1],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [31]:
# 3) Crear un array z3 3x4 lleno de ceros salvo la última fila que será el rango entre 5 y 8.

In [44]:
arr1= np.zeros([3,4]) 
arr2 = np.reshape(np.arange(5,9) , [1,4])
z3 = np.concatenate((arr1, arr2))  
z3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [5., 6., 7., 8.]])