In [26]:
import tensorflow as tf

**Ejercicio 1**

In [27]:
a = tf.add(3,5)

In [28]:
print(a)

tf.Tensor(8, shape=(), dtype=int32)


In [29]:
tf.print(a)

8


**Ejercicio 2**

In [30]:
x = 2
y = 3

In [31]:
op1 = tf.add(x,y)

In [32]:
op2 = tf.multiply(x,y)

In [33]:
op3 = tf.pow(op2, op1)

In [34]:
tf.print(op3)

7776


**Ejercicio 3**

In [35]:
x = 2
y = 3

In [36]:
op1 = tf.add(x,y)
op2 = tf.multiply(x,y)
op3 = tf.pow(op2, op1)
useless = tf.multiply(x , op1)
tf.print(op3)

7776


**Ejercicio 4**

In [37]:
x = 2
y = 3
op1 = tf.add(x,y)
op2 = tf.multiply(x,y)
op3 = tf.pow(op2, op1)
op4 = tf.multiply(x, op1)
tf.print(op3, op4)

7776 10


**Paralelización**

In [40]:
print(tf.config.list_physical_devices('GPU'))
print(tf.test.gpu_device_name())

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
/device:GPU:0


In [41]:
with tf.device('/gpu:0'):
  a = tf.constant([1.0, 2.0, 3.0],name=0)
  b = tf.constant([1.0, 2.0, 5.0],name=0)
  c = tf.multiply(a,b)
  tf.print(c)

[1 4 15]


**Eager execution**

In [1]:
import tensorflow as tf

In [2]:
tf.executing_eagerly()

True

In [3]:
print(tf.add([1,2],[2,1]))

tf.Tensor([3 3], shape=(2,), dtype=int32)


In [4]:
print(tf.square(5))

tf.Tensor(25, shape=(), dtype=int32)


In [5]:
print(tf.reduce_sum([1,2,3]))

tf.Tensor(6, shape=(), dtype=int32)


In [6]:
print(tf.io.encode_base64('Hello world'))

tf.Tensor(b'SGVsbG8gd29ybGQ', shape=(), dtype=string)


In [8]:
x = tf.matmul([[1]],[[2,3]])

In [10]:
print(x.shape)
print(x.dtype)

(1, 2)
<dtype: 'int32'>


**Numpy y Tensorflow**

In [11]:
import numpy as np

In [12]:
many_ones =  np.ones([3,3])

In [17]:
print(many_ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [13]:
tensor = tf.multiply(many_ones, 42)

In [14]:
print(tensor)

tf.Tensor(
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]], shape=(3, 3), dtype=float64)


In [15]:
print(np.add(tensor, 1))

[[43. 43. 43.]
 [43. 43. 43.]
 [43. 43. 43.]]


In [16]:
print(type(tensor))

<class 'tensorflow.python.framework.ops.EagerTensor'>
