In [10]:
%ls

 El volumen de la unidad C no tiene etiqueta.
 El número de serie del volumen es: 2E84-B77B

 Directorio de C:\Users\jnieto\source\jupiter

08/07/2020  07:51    <DIR>          .
08/07/2020  07:51    <DIR>          ..
12/06/2020  08:16    <DIR>          .ipynb_checkpoints
06/06/2020  13:43    <DIR>          20200606_001_practica01
06/06/2020  16:39    <DIR>          20200606_002_practica02
06/06/2020  16:35    <DIR>          20200606_juan_nieto
13/06/2020  11:18    <DIR>          20200613_juan_nieto
09/07/2020  10:05    <DIR>          20200620_pandas_matplotlib
27/06/2020  12:16    <DIR>          20200624_001_practica01
02/07/2020  20:36    <DIR>          20200624_002_practica02
08/07/2020  07:54    <DIR>          20200627_scipy_scikitlearn
26/06/2020  23:14    <DIR>          intro_numpy
28/06/2020  00:05    <DIR>          intro_sympy
20/06/2020  23:35    <DIR>          matplotlib
07/07/2020  22:25    <DIR>          Pokemon
27/06/2020  11:40    <DIR>          scikit
27/06/2020  08:51   

In [15]:
from scipy import io as spio
import numpy as np

a = np.ones((3, 3)) # matriz de 3x3 de unos
spio.savemat('file.mat', {'a': a}) # se vuelca dictionary en el archivo (out)
data = spio.loadmat('file.mat') # cargar archivo .mat (in)
data['a']

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
%matplotlib inline

In [34]:
import matplotlib.pyplot as plt
plt.imread('data/fname.jpg') # transforma la imagen en array de bytes


array([[[161, 161, 161],
        [208, 208, 208],
        [210, 210, 210],
        ...,
        [209, 209, 209],
        [209, 209, 209],
        [154, 154, 154]],

       [[204, 204, 204],
        [251, 251, 251],
        [253, 253, 253],
        ...,
        [253, 253, 253],
        [253, 253, 253],
        [254, 254, 254]],

       [[206, 206, 206],
        [252, 252, 252],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [254, 254, 254]],

       ...,

       [[192, 192, 192],
        [248, 248, 248],
        [247, 247, 247],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[183, 183, 183],
        [245, 245, 245],
        [248, 248, 248],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[176, 176, 176],
        [243, 243, 243],
        [251, 251, 251],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

In [36]:
 # Calcular la determinante de una matriz cuadrática:

In [44]:
from scipy import linalg
arr = np.array([[1,2],
                [3,4]],dtype='int32')
linalg.det(arr)

-2.0

In [47]:
arr = np.array([[1, 2],
                [3, 4]])
arr = linalg.inv(arr)
arr

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [68]:
# [(A*A^-1)*np.eye[2]]
np.eye(3,k=-1) # indice del diagonal

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [69]:
np.eye(2) # diagonal 2x2

array([[1., 0.],
       [0., 1.]])

In [70]:
np.eye(3,k=1) # k indice del diagonal

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [83]:
arr = ([[2,3],[4,6]])
try:
    linalg.inv(arr) #
except Exception as e:
    print("{0}: Error al obtener la inversa de una matriz singular." .format(str(e)))


singular matrix: Error al obtener la inversa de una matriz singular.


In [73]:
# Interpolaciones
from scipy.interpolate import interp1d