In [7]:
# bibliotecas, modulos requeridos
import numpy  as np
# from IPython.display import HTML
# from sympy import *
# import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
"""
1. Generar una matriz de 7 columnas por 9 filas.
a. Las primeras 3 columnas de la matriz tienen que tener el valor 0.
b. La cuarta columna debe tener el valor 0.5, excepto por el último valor de esa columna, que
tiene que ser 0.7.
c. Las otras tres columnas deben tener el valor 1.
d. Imprimir también el promedio de la última fila
"""

In [18]:
M = np.zeros([3,9],dtype='int32') 
N = np.ones([1,9],dtype='int32')*0.5 
P = np.ones([3,9],dtype='int32') 
#M,N,P
Z = np.concatenate((M,N,P))
Z = np.rot90(Z)
Z[8,3] = 0.7 # Z[(9-1,4-1)] , 9 fila, 4ta columna
Z

array([[0. , 0. , 0. , 0.5, 1. , 1. , 1. ],
       [0. , 0. , 0. , 0.5, 1. , 1. , 1. ],
       [0. , 0. , 0. , 0.5, 1. , 1. , 1. ],
       [0. , 0. , 0. , 0.5, 1. , 1. , 1. ],
       [0. , 0. , 0. , 0.5, 1. , 1. , 1. ],
       [0. , 0. , 0. , 0.5, 1. , 1. , 1. ],
       [0. , 0. , 0. , 0.5, 1. , 1. , 1. ],
       [0. , 0. , 0. , 0.5, 1. , 1. , 1. ],
       [0. , 0. , 0. , 0.7, 1. , 1. , 1. ]])

In [64]:
# promedio de la ultima fila
avg_last_row = np.average(Z,axis=1,weights=None)[8]
avg_last_row


0.5285714285714286

In [ ]:
"""
2. Crear 2 matrices de 5 x 5 con números enteros aleatorios desde el 1 al 10.
    a. Imprimir ambas matrices.
    b. Imprimir una tercer matiza que contenga 0 o 1 en los espacios, estos valores serán llenados
de la evaluación de igualdad de los valores de los campos anteriores (0 si son diferentes y 1 si
son iguales). """

In [117]:
from numpy.random import default_rng
rng = default_rng()
a = rng.integers(1,high=10, size=(5, 5),dtype='int64',endpoint=True)
b = rng.integers(1,high=10, size=(5, 5),dtype='int64',endpoint=True)
a

array([[ 1,  9,  3,  5,  6],
       [ 9,  1,  8,  6,  2],
       [ 3,  3,  2,  9,  7],
       [ 1,  1,  3,  9,  7],
       [10,  5, 10,  7,  6]], dtype=int64)

In [119]:
b

array([[ 8,  7,  2,  9,  4],
       [ 4, 10,  2,  9,  5],
       [ 2,  8,  1,  5,  6],
       [ 2,  3,  3,  2,  6],
       [10,  3,  2,  7,  1]], dtype=int64)

In [128]:
z= a==b
z

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False,  True, False, False],
       [ True, False, False,  True, False]])

In [130]:
z = np.array(z, dtype=int)
z

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [1, 0, 0, 1, 0]])