_Hasta ahora hemos visto los tipos de datos más básicos que nos ofrece Python: integer, real, complex, boolean, list, tuple...  Pero ¿no echas algo de menos? Efectivamente, los __arrays__. _

_En este notebook nos adentraremos en el paquete NumPy: aprenderemos a crear distintos arrays y a operar con ellos_.
Un array es un __bloque de memoria que contiene elementos del mismo tipo__. Básicamente:

* nos _recuerdan_ a los vectores, matrices, tensores...
* podemos almacenar el array con un nombre y acceder a sus __elementos__ mediante sus __índices__.
* ayudan a gestionar de manera eficiente la memoria y a acelerar los cálculos.


---

| Índice     | 0     | 1     | 2     | 3     | ...   | n-1   | n  |
| ---------- | :---: | :---: | :---: | :---: | :---: | :---: | :---: |
| Valor      | 2.1   | 3.6   | 7.8   | 1.5   | ...   | 5.4   | 6.3 |

---

__¿Qué solemos guardar en arrays?__

* Vectores y matrices.
* Datos de experimentos:
    - En distintos instantes discretos.
    - En distintos puntos del espacio.
* Resultado de evaluar funciones con los datos anteriores.
* Discretizaciones para usar algoritmos de: integración, derivación, interpolación...
* ... 


NumPy es un paquete fundamental para la programación científica que __proporciona un objeto tipo array__ para almacenar datos de forma eficiente y una serie de __funciones__ para operar y manipular esos datos.
Para usar NumPy lo primero que debemos hacer es importarlo:

In [2]:
import numpy as np

In [3]:
np.__version__

'1.18.1'

# Nuestro primer array

In [4]:
mi_primer_array = np.array([1,2,3,4])
mi_primer_array

array([1, 2, 3, 4])

In [5]:
print(mi_primer_array)

[1 2 3 4]


In [6]:
type(mi_primer_array)

numpy.ndarray

In [7]:
mi_primer_array.dtype

dtype('int32')

In [10]:
mi_segundo_array = np.array([[1,2,3],[4,5,6],[7,8,9]])
mi_segundo_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
mi_segundo_array = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
    ])
mi_segundo_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
np.sum(mi_primer_array)

10

In [14]:
np.max(mi_primer_array)

4

In [15]:
np.sin(mi_segundo_array)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

In [16]:
np.pi, np.e

(3.141592653589793, 2.718281828459045)

# Funciones para crear arrays

In [17]:
np.zeros([10,10])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [18]:
np.empty([10])

array([2.37663529e-312, 2.58883487e-312, 2.41907520e-312, 2.44029516e-312,
       1.93101617e-312, 1.01855798e-312, 1.03977794e-312, 1.97345609e-312,
       1.11260483e-306, 2.22522596e-306])

np.empty([10])

In [21]:
from numpy import random 

In [23]:
np.ones([3,2])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

# Array de identidad

In [24]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Rangos

In [26]:
a = np.arange(0,5)
a

array([0, 1, 2, 3, 4])

In [27]:
b = np.arange(1,5)
b

array([1, 2, 3, 4])

In [30]:
np.arange(0,11,3)


array([0, 3, 6, 9])

# Linspace

In [32]:
np.linspace(0,10,30)

array([ 0.        ,  0.34482759,  0.68965517,  1.03448276,  1.37931034,
        1.72413793,  2.06896552,  2.4137931 ,  2.75862069,  3.10344828,
        3.44827586,  3.79310345,  4.13793103,  4.48275862,  4.82758621,
        5.17241379,  5.51724138,  5.86206897,  6.20689655,  6.55172414,
        6.89655172,  7.24137931,  7.5862069 ,  7.93103448,  8.27586207,
        8.62068966,  8.96551724,  9.31034483,  9.65517241, 10.        ])

# Reshape

In [41]:
a = np.arange(1,7)
a

array([1, 2, 3, 4, 5, 6])

In [43]:
b = np.reshape(a, [2,3])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
N = a.reshape([3,2])
N

array([[1, 2],
       [3, 4],
       [5, 6]])

# Operaciones

In [59]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [61]:
arr *2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [62]:
np.tanh(arr)

array([0.        , 0.76159416, 0.96402758, 0.99505475, 0.9993293 ,
       0.9999092 , 0.99998771, 0.99999834, 0.99999977, 0.99999997,
       1.        ])

# Operaciones con dos arreglos

In [63]:
arr1 = np.arange(0,11)  
arr2 = np.arange(20,31)
arr1, arr2

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]))

In [65]:
arr1 + arr2

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

In [67]:
arr1*arr2

array([  0,  21,  44,  69,  96, 125, 156, 189, 224, 261, 300])

# Comparaciones

In [69]:
arr1 > arr2

array([False, False, False, False, False, False, False, False, False,
       False, False])

# Caracteristicas de los arreglos

## 1) Homogeneidad

In [71]:
lista = [1, 1+2j, True, 'Hola mundo']
lista

[1, (1+2j), True, 'Hola mundo']

In [73]:
array = np.array([1, 1+2j, True, 'Hola mundo'])
array

array(['1', '(1+2j)', 'True', 'Hola mundo'], dtype='<U64')

## 2) Tamaño fijo en el momento de la creación

In [74]:
print(id(lista))

2179924151688


In [75]:
lista.append('fluidos')
lista

[1, (1+2j), True, 'Hola mundo', 'fluidos']

In [76]:
print(id(lista))

2179924151688


## 3) Eficiencia

In [85]:
lista = list(range(0,100000000))
type(lista)

list

In [86]:
%%timeit
sum(lista)

6.11 s ± 158 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [101]:
array = np.arange(0,11,dtype='int64')

In [102]:
type(array)

numpy.ndarray

In [103]:
%%timeit
sum(array)

5.38 µs ± 199 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [24]:
# promedios con pesos
# numpy.average(a, axis=None, weights=None, returned=False)[source]
# axis=0, cols
# axis=1, rows
b = np.array(np.arange(1,11,dtype='int32')) 
w = np.array(np.arange(10, 0, -1,dtype='int32'))
b,w
# avg = np.average(b, weights=w)
# avg = sum(a * weights) / sum(weights)
#avg


(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1]))

In [26]:
# generar 10 numeros aleatorios de punto flotante y generar array
from numpy.random import default_rng
rng = default_rng()
vals = rng.standard_normal(10)
vals 


array([-0.02983077,  1.59175891, -1.18697031,  0.83285129,  2.27368755,
        0.16577514, -0.61383236, -1.56446239,  2.79392929,  1.02338362])

In [31]:
# generar 10 enteros desde 0 hasta 11-1
# Generator.integer(low, high=None, size=None, dtype=np.int64, endpoint=False)
rng = np.random.default_rng()
rng.integers(11, size=10)

array([ 4,  0, 10,  3,  9,  6, 10,  1,  4,  7], dtype=int64)

In [49]:
# array de 2x4, desde 0 hasta 5 - 1
a = rng.integers(5, size=(2, 4))
# desde 1 hasta 6 - 1, arrary de 2x4, enteros de 64 bits
a = rng.integers(1,high=6, size=(2, 4),dtype='int64')
a

array([[5, 4, 3, 5],
       [4, 5, 1, 3]], dtype=int64)